#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         String-Scanf
version:      2.1
version_from: lib/String/Scanf.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
